### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by Geal**

### CODE REVIEW

**Comment by KannarFr** [comment]
\o/

**Comment by KannarFr** [comment]
Closed in favor of https://github.com/CleverCloud/biscuit-java/pull/35.

**Comment by Geal** [comment]
(reopening this since I can't push on the branch in #35)
@Korbik did some awesome work in getting biscuit-java to 2.0! It's in good shape now and can be tested (let's wait a bit before publishing)

**Comment by Keruspe** [comment]
[Switch from Either to Exceptions](https://github.com/CleverCloud/biscuit-java/pull/33/commits/e78559475991cbd5f5793334db91c864a511a162) => :sob:

**Comment by Korbik** [comment]
> [Switch from Either to Exceptions](https://github.com/CleverCloud/biscuit-java/pull/33/commits/e78559475991cbd5f5793334db91c864a511a162) => 😭

Trust me I tried to avoid it but without syntaxic sugar from Scala, Haskell or Rust. It was too painful to use. 
https://github.com/Korbik/biscuit-java/commit/4ffb88f616f56db2e2b10dbea1f5f64f6d24b0c2

https://github.com/Korbik/biscuit-java/blob/java_examples/src/test/java/com/clevercloud/biscuit/token/ExampleTest.java

**Comment by KannarFr** [comment]
I rebased master. 

@Korbik you are still the author of the commits I don't know why GitHub doesn't show ur avatar on the commits as it's done for @Geal and me. If you know the reason, do not hesitate to tell me and I'll change it.

Can we consider the job is done for v2.0?

**Comment by Keruspe** [comment]
@KannarFr my blind guess is that `cedric.corbiere[AT]elitt[DOT]com` is not registered in @Korbik github account

**Comment by Korbik** [comment]
> @KannarFr my blind guess is that `cedric.corbiere[AT]elitt[DOT]com` is not registered in @Korbik github account

Wrong email in the commit. I should have changed it.

**Comment by Korbik** [comment]
> I rebased master.
> 
> @Korbik you are still the author of the commits I don't know why GitHub doesn't show ur avatar on the commits as it's done for @Geal and me. If you know the reason, do not hesitate to tell me and I'll change it.
> 
> Can we consider the job is done for v2.0?

The API won't move but I still needs to migrate to junit-5 and implements the tests based on samples.json.

I will rewrite my history to set the right email.

**Comment by Korbik** [comment]
Now we can enter in beta phase. And we will be able to release soon if we don't have too much bugs. All the current tests are okay: 
* Existing tests have migrated and are all passed
* Use of the new samples.json for testing behavior is valid

**Pull request merged**
