### PR TITLE
Caveats to world

### PR DESCRIPTION
**Pull request by KannarFr**
Add caveats to world for their print during `print_world()`. This is an opportunity to facilitate the debug :).

### CODE REVIEW

**Comment by Geal** [comment]
LGTM. hy is the CI failing again?

**Comment by KannarFr** [comment]
The CI has already worked?

```
$ wget https://github.com/protocolbuffers/protobuf/archive/v3.11.0.tar.gz
$ tar xvf v3.11.0.tar.gz
$ pushd protobuf-3.11.0 && ./configure --prefix=/usr && make && sudo make install && popd
~/build/CleverCloud/biscuit-java/protobuf-3.11.0 ~/build/CleverCloud/biscuit-java
/home/travis/.travis/functions: line 109: ./configure: No such file or directory
The command "pushd protobuf-3.11.0 && ./configure --prefix=/usr && make && sudo make install && popd" failed and exited with 127 during .
```

**Comment by KannarFr** [comment]
@Geal

**Comment by KannarFr** [comment]
Verifier's world should have the token's caveats too, right?

**Comment by KannarFr** [comment]
@Geal

**Pull request merged**
